version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - sturdy_palm_tree
networks:
  sturdy_palm_tree:
    driver: bridge
